restore dependencies for clang build
Summary:
public
oops, last commit unintentionally removed the clang_plugin dependency of the
clang target.

Reviewed By: jberdine

Differential Revision: D2769897

fb-gh-sync-id: 95cda88

diff --git a/Makefile.in b/Makefile.in
--- a/Makefile.in
+++ b/Makefile.in
@@ -36,6 +36,20 @@ else
 	$(MAKE) -C $(INFER_DIR) java
 endif
 
+clang:
+ifneq (@BUILD_C_ANALYZERS@,yes)
+	@echo
+	@echo "  error: clang analyzers disabled by ./configure"
+	@echo "  to enable them again, see"
+	@echo
+	@echo "  ./configure --help"
+	@echo
+	@exit 1
+else
+	$(MAKE) -C $(INFER_DIR) clang
+endif
+
+ifeq (@BUILD_C_ANALYZERS@,yes)
 clang_setup:
 	export CC="@CC@" CFLAGS="@CFLAGS@"; \
 	export CXX="@CXX@" CXXFLAGS="@CXXFLAGS@"; \
@@ -59,17 +73,7 @@ clang_plugin: clang_setup
 	  CLANG_PREFIX=@CLANG_PREFIX@ \
 	  CLANG_INCLUDES=@CLANG_INCLUDES@
 
-clang:
-ifneq (@BUILD_C_ANALYZERS@,yes)
-	@echo
-	@echo "  error: clang analyzers disabled by ./configure"
-	@echo "  to enable them again, see"
-	@echo
-	@echo "  ./configure --help"
-	@echo
-	@exit 1
-else
-	$(MAKE) -C $(INFER_DIR) clang
+clang: clang_plugin
 endif
 
 buck_test: $(INFER_ANALYZERS)
