[make] make sure no command fails
Summary:
Run with `SHELL = bash -e -u -o pipefail` to catch many kinds of failures. We
were silently failing during `make install` because of some missing escaping,
and the failure was hidden because it was happening inside a bash `for` loop.
This fixes the escaping issue and makes sure such issues will result in an
error as of now.

Also removes dangerous `find -exec` instances: `find` will `exit 0` event if
some commands failed.

Fixes #887

Reviewed By: mbouaziz

Differential Revision: D7569054

fbshipit-source-id: 542fe50

diff --git a/Makefile.config b/Makefile.config
--- a/Makefile.config
+++ b/Makefile.config
@@ -6,7 +6,7 @@
 # of patent rights can be found in the PATENTS file in the same directory.
 
 ORIG_SHELL = $(shell echo "$$SHELL")
-SHELL = bash
+SHELL = bash -e -o pipefail -u
 
 ORIG_SHELL_PATH = $(shell printf "%s" "$$PATH")
 
@@ -153,10 +153,10 @@ else
 # Detect if we are already wrapped inside a silent_on_success call and try not to clutter the output
 # too much in that case.
 define silent_on_success
-  if [ "$$INSIDE_SILENT_ON_SUCCESS" = 1 ]; then \
-    echo "*** inner $(1)"; \
-    echo "*** inner command: $(2)"; \
-    echo "*** inner CWD: $(CURDIR)"; \
+  if [ -n "$${INSIDE_SILENT_ON_SUCCESS-}" ]; then \
+    echo '*** inner $(1)'; \
+    echo '*** inner command: $(2)'; \
+    echo '*** inner CWD: $(CURDIR)'; \
     ($(2)); \
     exit $$?; \
   fi; \
@@ -165,7 +165,7 @@ define silent_on_success
   UNIX_START_DATE=$$(date +"%s"); \
   HUMAN_START_DATE=$$(date +"%H:%M:%S"); \
   if [ -z $(SILENT) ]; then \
-    printf "[%s][%$(MAX_PID_SIZE)s] $(TERM_INFO)%s...$(TERM_RESET)\n" \
+    printf '[%s][%$(MAX_PID_SIZE)s] $(TERM_INFO)%s...$(TERM_RESET)\n' \
       "$$HUMAN_START_DATE" "$$HASH" "$(1)"; \
   fi; \
   $(MKDIR_P) $(ABSOLUTE_ROOT_DIR)/_build_logs; \
@@ -173,9 +173,9 @@ define silent_on_success
          2>$(ABSOLUTE_ROOT_DIR)/_build_logs/cmd-$$HASH.err; \
   ERRCODE=$$?; \
   if [ $$ERRCODE != 0 ]; then \
-    echo "$(TERM_ERROR)[*ERROR**][$$HASH] *** ERROR $(1)$(TERM_RESET)" >&2; \
-    echo "$(TERM_ERROR)[*ERROR**][$$HASH] *** command: $(2)$(TERM_RESET)" >&2; \
-    echo "$(TERM_ERROR)[*ERROR**][$$HASH] *** CWD: $(CURDIR)$(TERM_RESET)" >&2; \
+    echo "$(TERM_ERROR)[*ERROR**][$$HASH] *** ERROR '$(1)'$(TERM_RESET)" >&2; \
+    echo "$(TERM_ERROR)[*ERROR**][$$HASH] *** command: '$(2)'$(TERM_RESET)" >&2; \
+    echo "$(TERM_ERROR)[*ERROR**][$$HASH] *** CWD: '$(CURDIR)'$(TERM_RESET)" >&2; \
     echo "$(TERM_ERROR)[*ERROR**][$$HASH] *** stdout:$(TERM_RESET)" >&2; \
     sed -e "s/^\(.*\)$$/$(TERM_ERROR)[*ERROR**][$$HASH]$(TERM_RESET) \1/" \
       $(ABSOLUTE_ROOT_DIR)/_build_logs/cmd-$$HASH.out; >&2; \
